# SPDX-FileCopyrightText: Be√±at Gartzia Arruabarrena <bgartzia@redhat.com>
#
# SPDX-License-Identifier: CC0-1.0

name: "Tests"
on:
  pull_request:
    branches:
      - "main"
permissions:
  contents: "read"

# Don't waste job slots on superseded code
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  # Pinned toolchain for linting
  ACTIONS_LINTS_TOOLCHAIN: 1.85.0

jobs:
  tests-integration-just-stable:
    name: "Integration Tests, just"
    runs-on: "ubuntu-24.04"
    container:
      image: "ghcr.io/trusted-execution-clusters/buildroot:latest"
      options: "--privileged"
    strategy:
      matrix:
        target-image-url:
          - "https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/42.20250929.3.0/x86_64/fedora-coreos-42.20250929.3.0-ostree.x86_64.ociarchive"
          - "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.19/4.19.0/rhcos-4.19.0-x86_64-ostree.x86_64.ociarchive"
          - "quay.io/trusted-execution-clusters/fedora-coreos@sha256:0eafb8b60f0329a743d42e7d4d286eb4b36fd096489fdda74d011d861e6692e6"
        test-finder:
          - grep -E "^ *test-.*$" | grep -v uki
        host-platform:
          - qemu-ovmf/fedora-42
        include:
          - target-image-url: "https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/42.20250929.3.0/x86_64/fedora-coreos-42.20250929.3.0-ostree.x86_64.ociarchive"
            host-platform: azure/20251013
            test-finder: grep -E "^ *test-.*$" | grep -v uki | grep -v test-secureboot-disabled
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v6
      - name: "Clone reference-values"
        uses: actions/checkout@v6
        with:
          repository: trusted-execution-clusters/reference-values
          path: test-data
      - name: "Install toolchain"
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - name: "Cache build artifacts"
        uses: Swatinem/rust-cache@v2
      - name: "Run just tests"
        run: |
          just -v \
            --set image ${{ matrix.target-image-url }} \
            --set host_platform ${{ matrix.host-platform }} \
              $(just -l | ${{ matrix.test-finder }})
